/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  course: [
    { type: 'autogenerated', dirName: 'course' }
  ],
  duxapp: [
    { type: 'autogenerated', dirName: 'duxapp' },
  ],
  duxui: [
    { type: 'autogenerated', dirName: 'duxui' },
  ],
  app: [
    { type: 'autogenerated', dirName: 'app' },
  ],
  update: [
    { type: 'doc', id: 'update/start' },
    { type: 'doc', id: 'update/2025-12-26' },
    { type: 'doc', id: 'update/2025-12-19' },
    { type: 'doc', id: 'update/2025-11-16' },
    { type: 'doc', id: 'update/2025-08-30' },
    { type: 'doc', id: 'update/2025-08-08' },
    { type: 'doc', id: 'update/2025-07-25' },
    { type: 'doc', id: 'update/2025-07-17' },
    { type: 'doc', id: 'update/2025-07-11' },
    { type: 'doc', id: 'update/2025-07-05' },
    { type: 'doc', id: 'update/2025-06-25' },
    { type: 'doc', id: 'update/2025-06-24' },
    { type: 'doc', id: 'update/2025-06-18' },
    { type: 'doc', id: 'update/2025-06-16' },
    { type: 'doc', id: 'update/2025-06-14' },
    { type: 'doc', id: 'update/2025-06-12' },
    { type: 'doc', id: 'update/2025-06-10' },
    { type: 'doc', id: 'update/2025-06-04' },
    { type: 'doc', id: 'update/2025-05-29' },
    { type: 'doc', id: 'update/2025-05-16' },
    { type: 'doc', id: 'update/2025-05-12' },
    { type: 'doc', id: 'update/2025-05-07' },
    { type: 'doc', id: 'update/2025-04-16' },
    { type: 'doc', id: 'update/2025-03-29' },
    { type: 'doc', id: 'update/2025-03-05' },
    { type: 'doc', id: 'update/2025-01-13' },
    { type: 'doc', id: 'update/2025-01-06' },
    { type: 'doc', id: 'update/2025-01-01' },
    { type: 'doc', id: 'update/2024-12-18' },
    { type: 'doc', id: 'update/2024-12-11' },
    { type: 'doc', id: 'update/2024-12-09' },
    { type: 'doc', id: 'update/2024-12-06' },
    { type: 'doc', id: 'update/2024-12-04' },
    { type: 'doc', id: 'update/2024-12-02' },
    { type: 'doc', id: 'update/2024-11-29' },
    { type: 'doc', id: 'update/2024-11-22' },
    { type: 'doc', id: 'update/2024-11-18' },
    { type: 'doc', id: 'update/2024-11-08' },
    { type: 'doc', id: 'update/2024-11-06' }
  ],
  contact: [
    { type: 'autogenerated', dirName: 'contact' },
  ]
};

module.exports = sidebars;
